// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/car_communication.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CarCommunicationApp {

  /// <summary>Holder for reflection information generated from Protos/car_communication.proto</summary>
  public static partial class CarCommunicationReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/car_communication.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CarCommunicationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Qcm90b3MvY2FyX2NvbW11bmljYXRpb24ucHJvdG8SE0NhckNvbW11bmlj",
            "YXRpb25BcHAirgEKDlNlcnZlclJlc3BvbnNlEjwKB2NvbW1hbmQYASABKA4y",
            "Ky5DYXJDb21tdW5pY2F0aW9uQXBwLlNlcnZlclJlc3BvbnNlLkNvbW1hbmQi",
            "XgoHQ29tbWFuZBIICgRMRUZUEAASCQoFUklHSFQQARILCgdGT1JXQVJEEAIS",
            "DAoIQkFDS1dBUkQQAxIICgRTVE9QEAQSDAoIUE9XRVJPRkYQBRILCgdSRVNQ",
            "QVdOEAYiuAEKE0Rpc3RhbmNlU2Vuc29yc0RhdGESGwoTZnJvbnRfbGVmdF9k",
            "aXN0YW5jZRgBIAEoAhIWCg5mcm9udF9kaXN0YW5jZRgCIAEoAhIcChRmcm9u",
            "dF9yaWdodF9kaXN0YW5jZRgDIAEoAhIaChJiYWNrX2xlZnRfZGlzdGFuY2UY",
            "BCABKAISFQoNYmFja19kaXN0YW5jZRgFIAEoAhIbChNiYWNrX3JpZ2h0X2Rp",
            "c3RhbmNlGAYgASgCIiYKClJvdXRlckRhdGESCgoCaWQYASABKAkSDAoEcnNz",
            "aRgCIAEoAiKJAgoNQ2xpZW50UmVxdWVzdBIOCgZjYXJfaWQYASABKAkSFAoM",
            "Y2FtZXJhX2ltYWdlGAIgASgMEkcKFWRpc3RhbmNlX3NlbnNvcnNfZGF0YRgD",
            "IAEoCzIoLkNhckNvbW11bmljYXRpb25BcHAuRGlzdGFuY2VTZW5zb3JzRGF0",
            "YRI1Cgxyb3V0ZXJzX2RhdGEYBCADKAsyHy5DYXJDb21tdW5pY2F0aW9uQXBw",
            "LlJvdXRlckRhdGESHAoUYm94ZXNfaW5fY2FtZXJhX3ZpZXcYBSABKAgSGgoS",
            "Y2FyX2NvbGxpc2lvbl9kYXRhGAYgASgIEhgKEHFyX2NvZGVfbWV0YWRhdGEY",
            "ByABKAkyZwoNQ29tbXVuaWNhdGlvbhJWCgtTZW5kUmVxdWVzdBIiLkNhckNv",
            "bW11bmljYXRpb25BcHAuQ2xpZW50UmVxdWVzdBojLkNhckNvbW11bmljYXRp",
            "b25BcHAuU2VydmVyUmVzcG9uc2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CarCommunicationApp.ServerResponse), global::CarCommunicationApp.ServerResponse.Parser, new[]{ "Command" }, null, new[]{ typeof(global::CarCommunicationApp.ServerResponse.Types.Command) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CarCommunicationApp.DistanceSensorsData), global::CarCommunicationApp.DistanceSensorsData.Parser, new[]{ "FrontLeftDistance", "FrontDistance", "FrontRightDistance", "BackLeftDistance", "BackDistance", "BackRightDistance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CarCommunicationApp.RouterData), global::CarCommunicationApp.RouterData.Parser, new[]{ "Id", "Rssi" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CarCommunicationApp.ClientRequest), global::CarCommunicationApp.ClientRequest.Parser, new[]{ "CarId", "CameraImage", "DistanceSensorsData", "RoutersData", "BoxesInCameraView", "CarCollisionData", "QrCodeMetadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ServerResponse : pb::IMessage<ServerResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerResponse> _parser = new pb::MessageParser<ServerResponse>(() => new ServerResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CarCommunicationApp.CarCommunicationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerResponse(ServerResponse other) : this() {
      command_ = other.command_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerResponse Clone() {
      return new ServerResponse(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 1;
    private global::CarCommunicationApp.ServerResponse.Types.Command command_ = global::CarCommunicationApp.ServerResponse.Types.Command.Left;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CarCommunicationApp.ServerResponse.Types.Command Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Command != other.Command) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Command != global::CarCommunicationApp.ServerResponse.Types.Command.Left) hash ^= Command.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Command != global::CarCommunicationApp.ServerResponse.Types.Command.Left) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Command != global::CarCommunicationApp.ServerResponse.Types.Command.Left) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Command != global::CarCommunicationApp.ServerResponse.Types.Command.Left) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerResponse other) {
      if (other == null) {
        return;
      }
      if (other.Command != global::CarCommunicationApp.ServerResponse.Types.Command.Left) {
        Command = other.Command;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Command = (global::CarCommunicationApp.ServerResponse.Types.Command) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Command = (global::CarCommunicationApp.ServerResponse.Types.Command) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ServerResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Command {
        /// <summary>
        /// dqn predict movement   
        /// </summary>
        [pbr::OriginalName("LEFT")] Left = 0,
        [pbr::OriginalName("RIGHT")] Right = 1,
        [pbr::OriginalName("FORWARD")] Forward = 2,
        [pbr::OriginalName("BACKWARD")] Backward = 3,
        [pbr::OriginalName("STOP")] Stop = 4,
        /// <summary>
        /// service decision
        /// </summary>
        [pbr::OriginalName("POWEROFF")] Poweroff = 5,
        /// <summary>
        /// virtual model only
        /// </summary>
        [pbr::OriginalName("RESPAWN")] Respawn = 6,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DistanceSensorsData : pb::IMessage<DistanceSensorsData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DistanceSensorsData> _parser = new pb::MessageParser<DistanceSensorsData>(() => new DistanceSensorsData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DistanceSensorsData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CarCommunicationApp.CarCommunicationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DistanceSensorsData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DistanceSensorsData(DistanceSensorsData other) : this() {
      frontLeftDistance_ = other.frontLeftDistance_;
      frontDistance_ = other.frontDistance_;
      frontRightDistance_ = other.frontRightDistance_;
      backLeftDistance_ = other.backLeftDistance_;
      backDistance_ = other.backDistance_;
      backRightDistance_ = other.backRightDistance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DistanceSensorsData Clone() {
      return new DistanceSensorsData(this);
    }

    /// <summary>Field number for the "front_left_distance" field.</summary>
    public const int FrontLeftDistanceFieldNumber = 1;
    private float frontLeftDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FrontLeftDistance {
      get { return frontLeftDistance_; }
      set {
        frontLeftDistance_ = value;
      }
    }

    /// <summary>Field number for the "front_distance" field.</summary>
    public const int FrontDistanceFieldNumber = 2;
    private float frontDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FrontDistance {
      get { return frontDistance_; }
      set {
        frontDistance_ = value;
      }
    }

    /// <summary>Field number for the "front_right_distance" field.</summary>
    public const int FrontRightDistanceFieldNumber = 3;
    private float frontRightDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FrontRightDistance {
      get { return frontRightDistance_; }
      set {
        frontRightDistance_ = value;
      }
    }

    /// <summary>Field number for the "back_left_distance" field.</summary>
    public const int BackLeftDistanceFieldNumber = 4;
    private float backLeftDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float BackLeftDistance {
      get { return backLeftDistance_; }
      set {
        backLeftDistance_ = value;
      }
    }

    /// <summary>Field number for the "back_distance" field.</summary>
    public const int BackDistanceFieldNumber = 5;
    private float backDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float BackDistance {
      get { return backDistance_; }
      set {
        backDistance_ = value;
      }
    }

    /// <summary>Field number for the "back_right_distance" field.</summary>
    public const int BackRightDistanceFieldNumber = 6;
    private float backRightDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float BackRightDistance {
      get { return backRightDistance_; }
      set {
        backRightDistance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DistanceSensorsData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DistanceSensorsData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FrontLeftDistance, other.FrontLeftDistance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FrontDistance, other.FrontDistance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FrontRightDistance, other.FrontRightDistance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BackLeftDistance, other.BackLeftDistance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BackDistance, other.BackDistance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BackRightDistance, other.BackRightDistance)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrontLeftDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FrontLeftDistance);
      if (FrontDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FrontDistance);
      if (FrontRightDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FrontRightDistance);
      if (BackLeftDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BackLeftDistance);
      if (BackDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BackDistance);
      if (BackRightDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BackRightDistance);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrontLeftDistance != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(FrontLeftDistance);
      }
      if (FrontDistance != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(FrontDistance);
      }
      if (FrontRightDistance != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(FrontRightDistance);
      }
      if (BackLeftDistance != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(BackLeftDistance);
      }
      if (BackDistance != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(BackDistance);
      }
      if (BackRightDistance != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(BackRightDistance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrontLeftDistance != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(FrontLeftDistance);
      }
      if (FrontDistance != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(FrontDistance);
      }
      if (FrontRightDistance != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(FrontRightDistance);
      }
      if (BackLeftDistance != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(BackLeftDistance);
      }
      if (BackDistance != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(BackDistance);
      }
      if (BackRightDistance != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(BackRightDistance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrontLeftDistance != 0F) {
        size += 1 + 4;
      }
      if (FrontDistance != 0F) {
        size += 1 + 4;
      }
      if (FrontRightDistance != 0F) {
        size += 1 + 4;
      }
      if (BackLeftDistance != 0F) {
        size += 1 + 4;
      }
      if (BackDistance != 0F) {
        size += 1 + 4;
      }
      if (BackRightDistance != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DistanceSensorsData other) {
      if (other == null) {
        return;
      }
      if (other.FrontLeftDistance != 0F) {
        FrontLeftDistance = other.FrontLeftDistance;
      }
      if (other.FrontDistance != 0F) {
        FrontDistance = other.FrontDistance;
      }
      if (other.FrontRightDistance != 0F) {
        FrontRightDistance = other.FrontRightDistance;
      }
      if (other.BackLeftDistance != 0F) {
        BackLeftDistance = other.BackLeftDistance;
      }
      if (other.BackDistance != 0F) {
        BackDistance = other.BackDistance;
      }
      if (other.BackRightDistance != 0F) {
        BackRightDistance = other.BackRightDistance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            FrontLeftDistance = input.ReadFloat();
            break;
          }
          case 21: {
            FrontDistance = input.ReadFloat();
            break;
          }
          case 29: {
            FrontRightDistance = input.ReadFloat();
            break;
          }
          case 37: {
            BackLeftDistance = input.ReadFloat();
            break;
          }
          case 45: {
            BackDistance = input.ReadFloat();
            break;
          }
          case 53: {
            BackRightDistance = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            FrontLeftDistance = input.ReadFloat();
            break;
          }
          case 21: {
            FrontDistance = input.ReadFloat();
            break;
          }
          case 29: {
            FrontRightDistance = input.ReadFloat();
            break;
          }
          case 37: {
            BackLeftDistance = input.ReadFloat();
            break;
          }
          case 45: {
            BackDistance = input.ReadFloat();
            break;
          }
          case 53: {
            BackRightDistance = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RouterData : pb::IMessage<RouterData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RouterData> _parser = new pb::MessageParser<RouterData>(() => new RouterData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RouterData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CarCommunicationApp.CarCommunicationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RouterData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RouterData(RouterData other) : this() {
      id_ = other.id_;
      rssi_ = other.rssi_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RouterData Clone() {
      return new RouterData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rssi" field.</summary>
    public const int RssiFieldNumber = 2;
    private float rssi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Rssi {
      get { return rssi_; }
      set {
        rssi_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RouterData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RouterData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rssi, other.Rssi)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Rssi != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rssi);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Rssi != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Rssi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Rssi != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Rssi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Rssi != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RouterData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Rssi != 0F) {
        Rssi = other.Rssi;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 21: {
            Rssi = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 21: {
            Rssi = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientRequest : pb::IMessage<ClientRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientRequest> _parser = new pb::MessageParser<ClientRequest>(() => new ClientRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CarCommunicationApp.CarCommunicationReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest(ClientRequest other) : this() {
      carId_ = other.carId_;
      cameraImage_ = other.cameraImage_;
      distanceSensorsData_ = other.distanceSensorsData_ != null ? other.distanceSensorsData_.Clone() : null;
      routersData_ = other.routersData_.Clone();
      boxesInCameraView_ = other.boxesInCameraView_;
      carCollisionData_ = other.carCollisionData_;
      qrCodeMetadata_ = other.qrCodeMetadata_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientRequest Clone() {
      return new ClientRequest(this);
    }

    /// <summary>Field number for the "car_id" field.</summary>
    public const int CarIdFieldNumber = 1;
    private string carId_ = "";
    /// <summary>
    /// real model data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CarId {
      get { return carId_; }
      set {
        carId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "camera_image" field.</summary>
    public const int CameraImageFieldNumber = 2;
    private pb::ByteString cameraImage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString CameraImage {
      get { return cameraImage_; }
      set {
        cameraImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "distance_sensors_data" field.</summary>
    public const int DistanceSensorsDataFieldNumber = 3;
    private global::CarCommunicationApp.DistanceSensorsData distanceSensorsData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CarCommunicationApp.DistanceSensorsData DistanceSensorsData {
      get { return distanceSensorsData_; }
      set {
        distanceSensorsData_ = value;
      }
    }

    /// <summary>Field number for the "routers_data" field.</summary>
    public const int RoutersDataFieldNumber = 4;
    private static readonly pb::FieldCodec<global::CarCommunicationApp.RouterData> _repeated_routersData_codec
        = pb::FieldCodec.ForMessage(34, global::CarCommunicationApp.RouterData.Parser);
    private readonly pbc::RepeatedField<global::CarCommunicationApp.RouterData> routersData_ = new pbc::RepeatedField<global::CarCommunicationApp.RouterData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CarCommunicationApp.RouterData> RoutersData {
      get { return routersData_; }
    }

    /// <summary>Field number for the "boxes_in_camera_view" field.</summary>
    public const int BoxesInCameraViewFieldNumber = 5;
    private bool boxesInCameraView_;
    /// <summary>
    /// virtual model data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BoxesInCameraView {
      get { return boxesInCameraView_; }
      set {
        boxesInCameraView_ = value;
      }
    }

    /// <summary>Field number for the "car_collision_data" field.</summary>
    public const int CarCollisionDataFieldNumber = 6;
    private bool carCollisionData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CarCollisionData {
      get { return carCollisionData_; }
      set {
        carCollisionData_ = value;
      }
    }

    /// <summary>Field number for the "qr_code_metadata" field.</summary>
    public const int QrCodeMetadataFieldNumber = 7;
    private string qrCodeMetadata_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string QrCodeMetadata {
      get { return qrCodeMetadata_; }
      set {
        qrCodeMetadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CarId != other.CarId) return false;
      if (CameraImage != other.CameraImage) return false;
      if (!object.Equals(DistanceSensorsData, other.DistanceSensorsData)) return false;
      if(!routersData_.Equals(other.routersData_)) return false;
      if (BoxesInCameraView != other.BoxesInCameraView) return false;
      if (CarCollisionData != other.CarCollisionData) return false;
      if (QrCodeMetadata != other.QrCodeMetadata) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CarId.Length != 0) hash ^= CarId.GetHashCode();
      if (CameraImage.Length != 0) hash ^= CameraImage.GetHashCode();
      if (distanceSensorsData_ != null) hash ^= DistanceSensorsData.GetHashCode();
      hash ^= routersData_.GetHashCode();
      if (BoxesInCameraView != false) hash ^= BoxesInCameraView.GetHashCode();
      if (CarCollisionData != false) hash ^= CarCollisionData.GetHashCode();
      if (QrCodeMetadata.Length != 0) hash ^= QrCodeMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CarId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CarId);
      }
      if (CameraImage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(CameraImage);
      }
      if (distanceSensorsData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DistanceSensorsData);
      }
      routersData_.WriteTo(output, _repeated_routersData_codec);
      if (BoxesInCameraView != false) {
        output.WriteRawTag(40);
        output.WriteBool(BoxesInCameraView);
      }
      if (CarCollisionData != false) {
        output.WriteRawTag(48);
        output.WriteBool(CarCollisionData);
      }
      if (QrCodeMetadata.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(QrCodeMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CarId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CarId);
      }
      if (CameraImage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(CameraImage);
      }
      if (distanceSensorsData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DistanceSensorsData);
      }
      routersData_.WriteTo(ref output, _repeated_routersData_codec);
      if (BoxesInCameraView != false) {
        output.WriteRawTag(40);
        output.WriteBool(BoxesInCameraView);
      }
      if (CarCollisionData != false) {
        output.WriteRawTag(48);
        output.WriteBool(CarCollisionData);
      }
      if (QrCodeMetadata.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(QrCodeMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CarId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CarId);
      }
      if (CameraImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CameraImage);
      }
      if (distanceSensorsData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DistanceSensorsData);
      }
      size += routersData_.CalculateSize(_repeated_routersData_codec);
      if (BoxesInCameraView != false) {
        size += 1 + 1;
      }
      if (CarCollisionData != false) {
        size += 1 + 1;
      }
      if (QrCodeMetadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QrCodeMetadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientRequest other) {
      if (other == null) {
        return;
      }
      if (other.CarId.Length != 0) {
        CarId = other.CarId;
      }
      if (other.CameraImage.Length != 0) {
        CameraImage = other.CameraImage;
      }
      if (other.distanceSensorsData_ != null) {
        if (distanceSensorsData_ == null) {
          DistanceSensorsData = new global::CarCommunicationApp.DistanceSensorsData();
        }
        DistanceSensorsData.MergeFrom(other.DistanceSensorsData);
      }
      routersData_.Add(other.routersData_);
      if (other.BoxesInCameraView != false) {
        BoxesInCameraView = other.BoxesInCameraView;
      }
      if (other.CarCollisionData != false) {
        CarCollisionData = other.CarCollisionData;
      }
      if (other.QrCodeMetadata.Length != 0) {
        QrCodeMetadata = other.QrCodeMetadata;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CarId = input.ReadString();
            break;
          }
          case 18: {
            CameraImage = input.ReadBytes();
            break;
          }
          case 26: {
            if (distanceSensorsData_ == null) {
              DistanceSensorsData = new global::CarCommunicationApp.DistanceSensorsData();
            }
            input.ReadMessage(DistanceSensorsData);
            break;
          }
          case 34: {
            routersData_.AddEntriesFrom(input, _repeated_routersData_codec);
            break;
          }
          case 40: {
            BoxesInCameraView = input.ReadBool();
            break;
          }
          case 48: {
            CarCollisionData = input.ReadBool();
            break;
          }
          case 58: {
            QrCodeMetadata = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CarId = input.ReadString();
            break;
          }
          case 18: {
            CameraImage = input.ReadBytes();
            break;
          }
          case 26: {
            if (distanceSensorsData_ == null) {
              DistanceSensorsData = new global::CarCommunicationApp.DistanceSensorsData();
            }
            input.ReadMessage(DistanceSensorsData);
            break;
          }
          case 34: {
            routersData_.AddEntriesFrom(ref input, _repeated_routersData_codec);
            break;
          }
          case 40: {
            BoxesInCameraView = input.ReadBool();
            break;
          }
          case 48: {
            CarCollisionData = input.ReadBool();
            break;
          }
          case 58: {
            QrCodeMetadata = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
