# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_communication.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63\x61r_communication.proto\x12\x13\x43\x61rCommunicationApp\"A\n\rCarParameters\x12\r\n\x05steer\x18\x01 \x01(\x02\x12\x0f\n\x07\x66orward\x18\x02 \x01(\x02\x12\x10\n\x08\x62\x61\x63kward\x18\x03 \x01(\x02\"\x82\x02\n\x0eServerResponse\x12<\n\x07\x63ommand\x18\x01 \x01(\x0e\x32+.CarCommunicationApp.ServerResponse.Command\x12:\n\x0e\x63\x61r_parameters\x18\x02 \x01(\x0b\x32\".CarCommunicationApp.CarParameters\"v\n\x07\x43ommand\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x12\x0b\n\x07\x46ORWARD\x10\x02\x12\x0c\n\x08\x42\x41\x43KWARD\x10\x03\x12\x08\n\x04STOP\x10\x04\x12\x08\n\x04NOOP\x10\x05\x12\x0c\n\x08POWEROFF\x10\x06\x12\x0b\n\x07RESPAWN\x10\x07\x12\x0c\n\x08MOVEMENT\x10\x08\"\xb8\x01\n\x13\x44istanceSensorsData\x12\x1b\n\x13\x66ront_left_distance\x18\x01 \x01(\x02\x12\x16\n\x0e\x66ront_distance\x18\x02 \x01(\x02\x12\x1c\n\x14\x66ront_right_distance\x18\x03 \x01(\x02\x12\x1a\n\x12\x62\x61\x63k_left_distance\x18\x04 \x01(\x02\x12\x15\n\rback_distance\x18\x05 \x01(\x02\x12\x1b\n\x13\x62\x61\x63k_right_distance\x18\x06 \x01(\x02\"&\n\nRouterData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04rssi\x18\x02 \x01(\x02\"\xd8\x02\n\rClientRequest\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\t\x12\x11\n\tcar_speed\x18\x02 \x01(\x02\x12:\n\x0e\x63\x61r_parameters\x18\x03 \x01(\x0b\x32\".CarCommunicationApp.CarParameters\x12\x14\n\x0c\x63\x61mera_image\x18\x04 \x01(\x0c\x12G\n\x15\x64istance_sensors_data\x18\x05 \x01(\x0b\x32(.CarCommunicationApp.DistanceSensorsData\x12\x35\n\x0crouters_data\x18\x06 \x03(\x0b\x32\x1f.CarCommunicationApp.RouterData\x12\x1c\n\x14\x62oxes_in_camera_view\x18\x07 \x01(\x08\x12\x1a\n\x12\x63\x61r_collision_data\x18\x08 \x01(\x08\x12\x18\n\x10qr_code_metadata\x18\t \x01(\t2g\n\rCommunication\x12V\n\x0bSendRequest\x12\".CarCommunicationApp.ClientRequest\x1a#.CarCommunicationApp.ServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'car_communication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CARPARAMETERS']._serialized_start=48
  _globals['_CARPARAMETERS']._serialized_end=113
  _globals['_SERVERRESPONSE']._serialized_start=116
  _globals['_SERVERRESPONSE']._serialized_end=374
  _globals['_SERVERRESPONSE_COMMAND']._serialized_start=256
  _globals['_SERVERRESPONSE_COMMAND']._serialized_end=374
  _globals['_DISTANCESENSORSDATA']._serialized_start=377
  _globals['_DISTANCESENSORSDATA']._serialized_end=561
  _globals['_ROUTERDATA']._serialized_start=563
  _globals['_ROUTERDATA']._serialized_end=601
  _globals['_CLIENTREQUEST']._serialized_start=604
  _globals['_CLIENTREQUEST']._serialized_end=948
  _globals['_COMMUNICATION']._serialized_start=950
  _globals['_COMMUNICATION']._serialized_end=1053
# @@protoc_insertion_point(module_scope)
