# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import car_communication_pb2 as car__communication__pb2


class CommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRequest = channel.unary_unary(
            "/CarCommunicationApp.Communication/SendRequest",
            request_serializer=car__communication__pb2.ClientRequest.SerializeToString,
            response_deserializer=car__communication__pb2.ServerResponse.FromString,
        )


class CommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendRequest": grpc.unary_unary_rpc_method_handler(
            servicer.SendRequest,
            request_deserializer=car__communication__pb2.ClientRequest.FromString,
            response_serializer=car__communication__pb2.ServerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "CarCommunicationApp.Communication", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Communication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRequest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/CarCommunicationApp.Communication/SendRequest",
            car__communication__pb2.ClientRequest.SerializeToString,
            car__communication__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
