[tool.poetry]
name = "grpc"
version = "0.1.0"
description = ""
authors = ["Max <avdeenkomaxim123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
grpcio = "^1.59.2"
grpcio-tools = "^1.59.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
